name: Bank Backend Pipeline

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - cicd

jobs:
  Continues-Integration_build_and_push:
    runs-on: ubuntu-latest
    env:
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      # ðŸ”¥ ADD MAVEN BUILD HERE
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
         java-version: '17'
         distribution: 'temurin'

      - name: Build Maven project (skip tests and skip dependency-check)
        run: mvn clean install -DskipTests -Ddependency-check.skip
      # ðŸ”¥ END MAVEN BUILD


      # Log in to AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Build Docker image
      - name: Build Docker image
        run: docker build -t bank-app-backend:latest .

      # Log in to ECR
      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

      # Tag Docker image
      - name: Tag Docker image
        run: docker tag bank-app-backend:latest ${{ secrets.ECR_REPO }}/bank-backendapi:${{ github.run_number }}

      # Push Docker image to ECR
      - name: Push image to ECR
        run: docker push ${{ secrets.ECR_REPO }}/bank-backendapi:${{ github.run_number }}

      # Clean up Docker images locally
      - name: Clean up Docker image locally
        run: |
          docker rmi bank-app-backend:latest
          docker rmi ${{ secrets.ECR_REPO }}/bank-backendapi:${{ github.run_number }}
