name: Static Code Analysis and Dependency Check analysis.

on:
  push:
    branches:
      - main

jobs:

  dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SetUp JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      # -----------------------------
      # Run dependency-check with OSS Index disabled
      # -----------------------------
      - name: Run Dependency Check
        run: |
          mvn org.owasp:dependency-check-maven:check \
            -DossIndexAnalyzerEnabled=false \
            -DnvdApiKey=${{ secrets.NVD_API_KEY_01 }} \
            -Dformat=ALL

          ls -la target
          cat target/dependency-check-report.csv || true

      - name: Upload to DefectDojo
        run: |
          chmod +x dependencycheck-defectdojoupload.sh
          sh ./dependencycheck-defectdojoupload.sh


  build:
    name: Build + SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          
      - name: Maven Clean Verify
        run: mvn clean verify -DnvdApiKey=${{ secrets.NVD_API_KEY_01 }}

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=cloud-solution-us
            -Dsonar.projectKey=bank-app-backend
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

